[package]
name = "bevy_window"
version = "0.13.2"
edition = "2021"
description = "Provides windowing functionality for Bevy Engine"
homepage = "https://bevyengine.org"
repository = "https://github.com/bevyengine/bevy"
license = "MIT OR Apache-2.0"
keywords = ["bevy"]

[features]
default = []
serialize = ["serde", "smol_str/serde"]

[dependencies]
# bevy
bevy_a11y = { path = "../bevy_a11y", version = "0.13.2" }
bevy_app = { path = "../bevy_app", version = "0.13.2" }
bevy_ecs = { path = "../bevy_ecs", version = "0.13.2" }
bevy_math = { path = "../bevy_math", version = "0.13.2" }
bevy_reflect = { path = "../bevy_reflect", version = "0.13.2", features = [
  "glam",
] }
bevy_utils = { path = "../bevy_utils", version = "0.13.2" }
# Used for close_on_esc
bevy_input = { path = "../bevy_input", version = "0.13.2" }

# other
serde = { version = "1.0", features = ["derive"], optional = true }
raw-window-handle = "0.6"
smol_str = "0.2"
winit = { version = "0.29", default-features = false }

[lints]
workspace = true
